name: Auto Merge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
  status: {}
jobs:
  automerge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
          MERGE_LABELS: "status/ready-to-merge"
          MERGE_REMOVE_LABELS: "status/ready-to-merge"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "30000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
